### ISSUE TITLE
Login & Registration

### ISSUE THREAD

**Issue by McMutton** [McMutton/AkashaNA#4]
Create login and registration views using Django Registration Redux

**Comment by JimmyJame** [comment]
we need at the begining at least 4 levels of permitions. 
1.- administrator: add, modify and edit permitions
2.- basic: basic information (phone number, email) about students and ex students
3.- medium level: level 2 plus, personal CV
4.- high level: level 2 + 3 + historical

**Comment by JimmyJame** [comment]
ups! I was wrong, this goes into another issue, well, about this, we need the posibility to everybody that we wich give them access. of course with different levels

**Comment by McMutton** [comment]
Views are done.
