### ISSUE TITLE
User Hierarchy

### ISSUE THREAD

**Issue by McMutton** [McMutton/AkashaNA#5]
We need to have a clear idea of how many authorization levels should we have, what are the privileges etc.

For example:

Default user: Can create new students
Teacher: Can add grades, can see course/grade history 
etc...

**Comment by JimmyJame** [comment]
we need at the begining at least 4 levels of permitions.
1.- administrator: add, modify and edit permitions
2.- basic: basic information (phone number, email) about students and ex students
3.- medium level: level 2 plus, personal CV
4.- high level: level 2 + 3 + historical

**Comment by McMutton** [comment]
Jimmy on level 4 you wrote "historical". These are the course grades right? 

If so, I cannot really see why accessing it would require a higher authorization level than accessing a person's home address or phone number.

Let's talk about the details on next meeting.
