### ISSUE TITLE
Courses

### ISSUE THREAD

**Issue by McMutton** [McMutton/AkashaNA#7]
Jimmy can you please detail me how the courses table should be structured?

**Comment by JimmyJame** [comment]
class Subjets(models.Model)
Introductory= models.CharField(max_length=128)
Psycology= models.CharField(max_length=128)
ISO= models.CharField(max_length=128)
Moral Philosofhy= models.CharField(max_length=128)
Symbolism= models.CharField(max_length=128)

**Comment by McMutton** [comment]
Hi Jimmy, this is actually the data itself no? I believe we need something like below. 

```
class Subjects(models.Model)
name=models.CharField(max_length=128)
```

So an example table would look like this:

id | name
------------ | -------------
1 | Introductory
2 | Psychology
3 | ISO
4 | Moral Philosophy
5 | Symbolism
