### ISSUE TITLE
Enrollment Model

### ISSUE THREAD

**Issue by McMutton** [McMutton/AkashaNA#8]
We need another model/table for the enrollment in order to link the students to the courses with their grades.

**Comment by JimmyJame** [comment]
Is because we need a relation many to many?

**Comment by JimmyJame** [comment]
I don't know what do you mean...

**Comment by McMutton** [comment]
Hi Jimmy, sorry for the confusion. This is exactly the same thing as the "Historic Notes" on #6. I will close this issue and we can continue from there.
